# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'data/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Style/StringLiterals:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/LineLength:
  Max: 150

Layout/SpaceAroundOperators:
  EnforcedStyle: require_spaces_in_assignment
  SpaceAroundOperators:
    - op: '='
    - op: '+'
    - op: '-'
    - op: '*'
    - op: '/'
    - op: '%'
    - op: '**'
    - op: '|'
    - op: '&'
    - op: '^'
    - op: '<'
    - op: '>'
    - op: '=='
    - op: '==='
    - op: '!='
    - op: '<=>'
    - op: '&&'
    - op: '||'

Naming/MethodName:
  AllowedRegex: '\?$'

Metrics/BlockNesting:
  Max: 5

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

RSpec/MultipleExpectations:
  Max: 2