name: "CD"
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show current working directory
        run: pwd

  deploy-blue:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy blue to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/minibank-clients
            git pull origin master > pull.log
            ./deploy.sh blue >>deploy.log

  deploy-green:
    runs-on: ubuntu-latest
    needs: deploy-blue

    steps:
      - name: Deploy green to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/minibank-clients
            git pull origin master
            ./deploy.sh blue >>deploy.log
